#!/bin/bash
# FTMap Enhanced - Guia de Uso Rápido

echo "🧬 FTMap Enhanced - Sistema Modular de Análise de Druggability"
echo "=============================================================="
echo ""

echo "📋 COMANDOS PRINCIPAIS:"
echo ""
echo "1. Análise básica completa:"
echo "   python ftmap_cli.py protein.pdb"
echo ""
echo "2. Análise rápida (recomendado para testes):"
echo "   python ftmap_cli.py protein.pdb --quick-mode --verbose"
echo ""
echo "3. Análise com saída customizada:"
echo "   python ftmap_cli.py protein.pdb --output ./meus_resultados"
echo ""
echo "4. Análise apenas de docking:"
echo "   python ftmap_cli.py protein.pdb --steps dock --output ./dock_results"
echo ""
echo "5. Resumir análise interrompida:"
echo "   python ftmap_cli.py protein.pdb --resume workflow_state.json"
echo ""

echo "📁 ESTRUTURA DE SAÍDA:"
echo ""
echo "ftmap_results/"
echo "├── docking_results/     # Poses de docking em JSON"
echo "├── clusters/           # Análise de clustering"
echo "├── features/           # Features extraídas"
echo "├── models/            # Modelos ML treinados"
echo "├── reports/           # Relatórios HTML"
echo "├── visualizations/    # Plots e imagens"
echo "└── workflow_state.json # Estado do workflow"
echo ""

echo "🔧 DEPENDÊNCIAS OPCIONAIS:"
echo ""
echo "Para funcionalidade completa (instale se disponível):"
echo "- AutoDock Vina: sudo apt install autodock-vina"
echo "- Open Babel: sudo apt install openbabel"
echo "- PyMOL: pip install pymol-open-source"
echo "- fpocket: Baixar de https://github.com/Discngine/fpocket"
echo ""

echo "✅ TESTE RÁPIDO:"
echo ""
echo "# Testar com proteína exemplo"
echo "cd /home/hipolito/girias/FtMap/FTMap/ftmap_enhanced_modular"
echo "python ftmap_cli.py data/input/pfpkii.pdb --quick-mode --verbose"
echo ""

echo "📊 VERIFICAR RESULTADOS:"
echo ""
echo "# Ver poses de docking"
echo "cat ftmap_results/docking_results/pfpkii_docking.json | head -20"
echo ""
echo "# Ver estado do workflow"
echo "cat ftmap_results/workflow_state.json"
echo ""

echo "🆘 AJUDA:"
echo ""
echo "python ftmap_cli.py --help    # Ver todas as opções"
echo "cat SYSTEM_STATUS_REPORT.md  # Status detalhado do sistema"
echo "cat README.md                # Documentação completa"
echo ""

echo "🎯 SISTEMA TESTADO E FUNCIONAL!"
echo "Data: $(date)"
echo "=============================================================="
